version: "3.5"

services:
  golangci-lint:
    image: golangci/golangci-lint:v2.0.2
    working_dir: /app
    volumes:
      - ..:/app:cached
      - ~/gocache:/gocache
      - ~/gomodcache:/gomodcache
    environment:
      - GOCACHE=/gocache
      - GOMODCACHE=/gomodcache
  goreleaser:
    build:
      context: .
      dockerfile: Dockerfile.build
    environment:
      - BUILDKITE_AGENT_JOB_API_SOCKET
      - BUILDKITE_AGENT_JOB_API_TOKEN
      - GOCACHE=/gocache
      - GOMODCACHE=/gomodcache
    working_dir: /go/src/github.com/buildkite/zstash
    volumes:
      - ..:/go/src/github.com/buildkite/zstash:cached
      - ~/gocache:/gocache
      - ~/gomodcache:/gomodcache      
      - ${BUILDKITE_AGENT_JOB_API_SOCKET}:${BUILDKITE_AGENT_JOB_API_SOCKET}
      - /var/run/docker.sock:/var/run/docker.sock
