agents:
  queue: hosted

cache:
  name: "golang-cache"
  paths:
    - "~/gocache"
    - "~/gomodcache"
  size: "100g"

steps:
  - group: ":mag: Quality Checks"
    key: quality-checks
    steps:
    - name: ":golangci-lint: lint"
      command: golangci-lint run --verbose --timeout 3m
      plugins:
        - docker-compose#v5.10.0:
            config: .buildkite/docker-compose.yaml
            run: golangci-lint
            tty: true
            progress: plain

    - name: ":go: test"
      artifact_paths:
        - cover-tree.svg
      commands:
        - go test -coverprofile cover.out ./...
        - go run github.com/nikolaydubina/go-cover-treemap@latest -coverprofile cover.out > cover-tree.svg
        - echo '<details><summary>Coverage tree map</summary><img src="artifact://cover-tree.svg" alt="Test coverage tree map" width="70%"></details>' | buildkite-agent annotate --style "info"
      plugins:
        - docker-compose#v5.10.0:
            config: .buildkite/docker-compose.yaml
            run: golangci-lint
            tty: true
            mount-buildkite-agent: true
            progress: plain

